name: Run tests and checks
description: Run tests and checks on node project

runs:
  using: 'composite'
  steps:
    - name: Lint
      run: npm run lint
      shell: bash

    - name: Tests
      run: npm run test
      shell: bash
