name: Build and deploy app

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy-netlify:
        type: boolean
        description: Enable Netlify deployment
        default: true
      deploy-vercel:
        type: boolean
        description: Enable Vercel deployment
        default: true
      # vercel-env:
      #   type: string
      #   description: Vercel environment
      #   default: 'production'

jobs:
  lint-and-tests:
    uses: ./.github/workflows/lint-and-tests.yml
  deploy-netlify:
    needs: lint-and-tests
    uses: ./.github/workflows/deploy-netlify.yml
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
    if: ${{ inputs.deploy-netlify || github.event_name == 'push' }}

  deploy-vercel:
    needs: lint-and-tests
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    if: ${{ inputs.deploy-vercel  || github.event_name == 'push' }}
