name: Build and deploy app

on:
  workflow_dispatch:
    inputs:
      deploy-netlify:
        type: boolean
        description: Enable Netlify deployment
        default: true
      deploy-vercel:
        type: boolean
        description: Enable Vercel deployment
        default: true
      vercel-env:
        type: string
        description: Vercel environment
        default: 'production'

jobs:
  lint-and-tests:
    uses: ./.github/workflows/lint-and-tests.yml
  deploy-netlify:
    needs: lint-and-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Deploy to Netlify production env
        uses: ./.github/actions/deploy-netlify
        if: ${{ inputs.deploy-netlify  }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
        timeout-minutes: 2
  deploy-vercel:
    needs: lint-and-tests
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./github/actions/setup-project

      - name: Deploy to Vercel production env
        uses: ./.github/actions/deploy-vercel
        if: ${{ inputs.deploy-vercel }}
        with:
          mode: ${{ inputs.vercel-env }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
