name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Configure node
        uses: ./github/actions/setup-project

      - name: Run tests
        uses: ./github/actions/run-checks-and-tests

      - name: Build app
        run: npm run build

<<<<<<< Updated upstream
      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Bulid for Vercel
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        timeout-minutes: 2
=======
      - name: Deploy to Vercel preview env
        uses: ./github/actions/deploy-vercel
        with:
          mode: 'preview'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
>>>>>>> Stashed changes
