name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Run tests
        uses: ./.github/actions/run-checks-and-tests

      - name: Build app
        run: npm run build

      - name: Deploy to Vercel preview env
        uses: ./.github/actions/deploy-vercel
        with:
          mode: 'preview'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
