name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  verify-pr:
    uses: ./.github/workflows/lint-and-tests.yml

  deploy-preview:
    needs: verify-pr
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Bulid for Vercel
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: |
          DEPLOY_OUTPUT="$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }})"
          DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep http | tail -n 1)
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
        timeout-minutes: 2

      - name: Comment with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const { DEPLOY_URL } = process.env;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview URL: ${DEPLOY_URL}`
            });
